<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Anemia en infantes y mujeres</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="G3_Informe_files/libs/clipboard/clipboard.min.js"></script>
<script src="G3_Informe_files/libs/quarto-html/quarto.js"></script>
<script src="G3_Informe_files/libs/quarto-html/popper.min.js"></script>
<script src="G3_Informe_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="G3_Informe_files/libs/quarto-html/anchor.min.js"></script>
<link href="G3_Informe_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="G3_Informe_files/libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="G3_Informe_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="G3_Informe_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="G3_Informe_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark">

<script src="G3_Informe_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="G3_Informe_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#análisis-de-los-casos-de-anemia-en-infantes-y-mujeres-de-12-a-49-años-en-el-perú-en-el-año-2022" id="toc-análisis-de-los-casos-de-anemia-en-infantes-y-mujeres-de-12-a-49-años-en-el-perú-en-el-año-2022" class="nav-link active" data-scroll-target="#análisis-de-los-casos-de-anemia-en-infantes-y-mujeres-de-12-a-49-años-en-el-perú-en-el-año-2022"><strong>Análisis de los casos de anemia en infantes y mujeres de 12 a 49 años en el Perú en el año 2022</strong></a>
  <ul class="collapse">
  <li><a href="#introducción" id="toc-introducción" class="nav-link" data-scroll-target="#introducción">1. Introducción</a>
  <ul class="collapse">
  <li><a href="#relevancia" id="toc-relevancia" class="nav-link" data-scroll-target="#relevancia">1.1 Relevancia</a></li>
  <li><a href="#objetivos" id="toc-objetivos" class="nav-link" data-scroll-target="#objetivos">1.2 Objetivos</a></li>
  <li><a href="#contexto" id="toc-contexto" class="nav-link" data-scroll-target="#contexto">1.3 Contexto</a></li>
  <li><a href="#instalación-y-carga-de-librerías" id="toc-instalación-y-carga-de-librerías" class="nav-link" data-scroll-target="#instalación-y-carga-de-librerías">1.4 Instalación y carga de librerías</a></li>
  </ul></li>
  <li><a href="#datos" id="toc-datos" class="nav-link" data-scroll-target="#datos">2. Datos</a>
  <ul class="collapse">
  <li><a href="#recolección-de-datos" id="toc-recolección-de-datos" class="nav-link" data-scroll-target="#recolección-de-datos">2.1 Recolección de datos</a></li>
  <li><a href="#población-objetivo-muestra-y-muestreo" id="toc-población-objetivo-muestra-y-muestreo" class="nav-link" data-scroll-target="#población-objetivo-muestra-y-muestreo">2.2 Población objetivo, muestra y muestreo</a></li>
  <li><a href="#variables" id="toc-variables" class="nav-link" data-scroll-target="#variables">2.3 Variables</a></li>
  </ul></li>
  <li><a href="#análisis-descriptivo-univariado" id="toc-análisis-descriptivo-univariado" class="nav-link" data-scroll-target="#análisis-descriptivo-univariado">3. Análisis descriptivo univariado</a>
  <ul class="collapse">
  <li><a href="#variables-numéricas" id="toc-variables-numéricas" class="nav-link" data-scroll-target="#variables-numéricas">3.1 Variables numéricas</a></li>
  <li><a href="#variables-categóricas" id="toc-variables-categóricas" class="nav-link" data-scroll-target="#variables-categóricas">3.2 Variables categóricas</a></li>
  </ul></li>
  <li><a href="#análisis-descriptivo-de-interacción" id="toc-análisis-descriptivo-de-interacción" class="nav-link" data-scroll-target="#análisis-descriptivo-de-interacción">4. Análisis descriptivo de interacción</a>
  <ul class="collapse">
  <li><a href="#edad-de-niños-vs.-frecuencias-de-anemia" id="toc-edad-de-niños-vs.-frecuencias-de-anemia" class="nav-link" data-scroll-target="#edad-de-niños-vs.-frecuencias-de-anemia">4.1 Edad de niños vs.&nbsp;frecuencias de anemia</a></li>
  <li><a href="#edad-de-mujeres-vs.-frecuencia-de-anemia" id="toc-edad-de-mujeres-vs.-frecuencia-de-anemia" class="nav-link" data-scroll-target="#edad-de-mujeres-vs.-frecuencia-de-anemia">4.2 Edad de mujeres vs.&nbsp;frecuencia de anemia</a></li>
  <li><a href="#regiones-vs.-nivel-de-anemia" id="toc-regiones-vs.-nivel-de-anemia" class="nav-link" data-scroll-target="#regiones-vs.-nivel-de-anemia">4.3 Regiones vs.&nbsp;nivel de anemia</a></li>
  <li><a href="#características-sociales" id="toc-características-sociales" class="nav-link" data-scroll-target="#características-sociales">4.4 Características sociales</a></li>
  </ul></li>
  <li><a href="#probabilidad-empírica" id="toc-probabilidad-empírica" class="nav-link" data-scroll-target="#probabilidad-empírica">5. Probabilidad empírica</a>
  <ul class="collapse">
  <li><a href="#variable-a-índice-de-riqueza" id="toc-variable-a-índice-de-riqueza" class="nav-link" data-scroll-target="#variable-a-índice-de-riqueza">5.1 Variable A: Índice de riqueza</a></li>
  <li><a href="#variable-b-nivel-de-anemia" id="toc-variable-b-nivel-de-anemia" class="nav-link" data-scroll-target="#variable-b-nivel-de-anemia">5.2 Variable B: Nivel de anemia</a></li>
  </ul></li>
  <li><a href="#probabilidad-condicional" id="toc-probabilidad-condicional" class="nav-link" data-scroll-target="#probabilidad-condicional">6. Probabilidad condicional</a>
  <ul class="collapse">
  <li><a href="#eventos-dependientes" id="toc-eventos-dependientes" class="nav-link" data-scroll-target="#eventos-dependientes">6.1 Eventos dependientes</a></li>
  <li><a href="#eventos-independientes" id="toc-eventos-independientes" class="nav-link" data-scroll-target="#eventos-independientes">6.2 Eventos independientes</a></li>
  </ul></li>
  <li><a href="#variables-aleatorias-discretas" id="toc-variables-aleatorias-discretas" class="nav-link" data-scroll-target="#variables-aleatorias-discretas">7. Variables aleatorias discretas</a>
  <ul class="collapse">
  <li><a href="#número-de-niños-con-un-determinado-nivel-de-anemia" id="toc-número-de-niños-con-un-determinado-nivel-de-anemia" class="nav-link" data-scroll-target="#número-de-niños-con-un-determinado-nivel-de-anemia">7.1 Número de niños con un determinado nivel de anemia</a></li>
  <li><a href="#número-de-madres-con-un-determinado-nivel-educativo" id="toc-número-de-madres-con-un-determinado-nivel-educativo" class="nav-link" data-scroll-target="#número-de-madres-con-un-determinado-nivel-educativo">7.2 Número de madres con un determinado nivel educativo</a></li>
  </ul></li>
  <li><a href="#variables-aleatorias-continuas" id="toc-variables-aleatorias-continuas" class="nav-link" data-scroll-target="#variables-aleatorias-continuas">8. Variables aleatorias continuas</a>
  <ul class="collapse">
  <li><a href="#hemoglobina-ajustada-en-función-de-la-latitud-gdl" id="toc-hemoglobina-ajustada-en-función-de-la-latitud-gdl" class="nav-link" data-scroll-target="#hemoglobina-ajustada-en-función-de-la-latitud-gdl">8.1 Hemoglobina ajustada en función de la latitud (<span class="math inline">\(g/dl\)</span>)</a></li>
  <li><a href="#peso-kg" id="toc-peso-kg" class="nav-link" data-scroll-target="#peso-kg">8.2 Peso (<span class="math inline">\(kg\)</span>)</a></li>
  </ul></li>
  <li><a href="#conclusiones" id="toc-conclusiones" class="nav-link" data-scroll-target="#conclusiones">9. Conclusiones</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Anemia en infantes y mujeres</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Colque Ordoñez, Patrick Fabrizio </p>
             <p>Rejas Albujar, Alejandro David </p>
             <p>Escobar Núñez, Alejandro Ismael </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<div class="quarto-figure quarto-figure-left">
<figure class="figure">
<p><img src="UTEC.png" class="img-fluid figure-img" width="252"></p>
</figure>
</div>
<section id="análisis-de-los-casos-de-anemia-en-infantes-y-mujeres-de-12-a-49-años-en-el-perú-en-el-año-2022" class="level1">
<h1><strong>Análisis de los casos de anemia en infantes y mujeres de 12 a 49 años en el Perú en el año 2022</strong></h1>
<section id="introducción" class="level2">
<h2 class="anchored" data-anchor-id="introducción">1. Introducción</h2>
<section id="relevancia" class="level3">
<h3 class="anchored" data-anchor-id="relevancia">1.1 Relevancia</h3>
<p>La anemia es un problema de salud pública de gran relevancia en nuestro país. La falta de hemoglobina en la sangre puede tener consecuencias graves, especialmente en niños y madres. Además, la anemia puede afectar el desarrollo físico y cognitivo de los niños y aumentar el riesgo de complicaciones en el embarazo para las madres; por lo tanto, comprender la prevalencia y severidad de la anemia en estos grupos es esencial para abordar adecuadamente este problema de salud en el país.</p>
</section>
<section id="objetivos" class="level3">
<h3 class="anchored" data-anchor-id="objetivos">1.2 Objetivos</h3>
<ul>
<li><p>Describir los casos de anemia y su severidad en niños y mujeres en el Perú en el año 2022.</p></li>
<li><p>Analizar el índice de anemia en las diversas regiones del Perú en el año 2022.</p></li>
<li><p>Describir las características sociales de los grupos vulnerables (niños y mujeres) a la anemia en el Perú en el año 2022.</p></li>
</ul>
</section>
<section id="contexto" class="level3">
<h3 class="anchored" data-anchor-id="contexto">1.3 Contexto</h3>
<p>En el mes de mayo del año 2022, se llevó a cabo en nuestro país la Encuesta Demográfica y de Salud Familiar, un estudio que recopiló datos de una muestra representativa de viviendas en todo el territorio peruano. Este estudio se basó en tres cuestionarios diseñados específicamente: uno dirigido a todos los miembros de cada hogar, otro enfocado en mujeres cuyas edades se encontraban en el rango de 12 a 49 años, y un tercero destinado a individuos de 15 años o más.</p>
<p>En el contexto de esta encuesta, se solicitó a los residentes de los hogares su participación en una evaluación destinada a conocer sus niveles de hemoglobina en la sangre, a la que podían optar por unirse o no.</p>
<p>La totalidad de la información recopilada en esta encuesta se encuentra disponible para consulta por parte de cualquier ciudadano en la base de datos del Instituto Nacional de Estadística e Informática (INEI). Los datos se presentan organizados en módulos temáticos, y nuestro enfoque recae en los análisis de los casos de anemia en infantes y mujeres.</p>
</section>
<section id="instalación-y-carga-de-librerías" class="level3">
<h3 class="anchored" data-anchor-id="instalación-y-carga-de-librerías">1.4 Instalación y carga de librerías</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gt)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rriskDistributions)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="datos" class="level2">
<h2 class="anchored" data-anchor-id="datos">2. Datos</h2>
<section id="recolección-de-datos" class="level3">
<h3 class="anchored" data-anchor-id="recolección-de-datos">2.1 Recolección de datos</h3>
<p>Los datos para este estudio se obtuvieron a partir de la Encuesta Demográfica y de Salud Familiar realizada en mayo de 2022 en el Perú. Se seleccionaron módulos específicos que eran relevantes para nuestro estudio sobre la anemia en niños y mujeres. Estos módulos incluían información sobre las características de los hogares y sus integrantes. El acceso a esta base de datos nos proporcionó una amplia cantidad de información relevante y detallada para nuestros objetivos de investigación.</p>
</section>
<section id="población-objetivo-muestra-y-muestreo" class="level3">
<h3 class="anchored" data-anchor-id="población-objetivo-muestra-y-muestreo">2.2 Población objetivo, muestra y muestreo</h3>
<ul>
<li><p><strong>Población:</strong> Miembros de los hogares de la Encuesta Demográfica y de Salud Familiar.</p></li>
<li><p><strong>Muestra:</strong> Mujeres de 12 a 49 años de edad y niños o niñas menores de 5 años residentes de los hogares particulares recogidos por la encuesta.</p></li>
<li><p><strong>Muestreo:</strong> Probabilístico por conglomerados.</p></li>
</ul>
</section>
<section id="variables" class="level3">
<h3 class="anchored" data-anchor-id="variables">2.3 Variables</h3>
<ul>
<li><p><strong>Tabla RECH0:</strong> Características del hogar</p></li>
<li><p><strong>Tabla RECH5:</strong> Peso y talla (anemia). Características de las mujeres de 12 a 49 años.</p></li>
<li><p><strong>Tabla REC0111:</strong> Datos básicos del MEF. Relación entre identificación del cuestionario individual e identificación del cuestionario del hogar.</p></li>
<li><p><strong>Tabla REC44:</strong> Peso y talla (anemia). Características de los infantes de 0 a 59 meses (5 años aproximadamente) seleccionados por hogar.</p></li>
<li><p><strong>Tabla RECH23:</strong> Características del hogar de los participantes. Estos contienen las características del modo de vida de los que respondieron la encuesta.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>REC0111 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"REC0111_clean.csv"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>RECH5 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"RECH5_clean.csv"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>REC44 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"REC44_clean.csv"</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>RECH23 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"RECH23_clean.csv"</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>RECH0 <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"RECH0_clean.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="análisis-descriptivo-univariado" class="level2">
<h2 class="anchored" data-anchor-id="análisis-descriptivo-univariado">3. Análisis descriptivo univariado</h2>
<section id="variables-numéricas" class="level3">
<h3 class="anchored" data-anchor-id="variables-numéricas">3.1 Variables numéricas</h3>
<section id="hemoglobina-de-niños" class="level4">
<h4 class="anchored" data-anchor-id="hemoglobina-de-niños">3.1.1 Hemoglobina de niños</h4>
<div class="cell">
<div class="cell-output-display">
<p><img src="G3_Informe_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Descriptores numéricos:</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Media</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mediana</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mínimo</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Máximo</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SD</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">11.25</td>
<td style="text-align: right;">11.3</td>
<td style="text-align: right;">4.4</td>
<td style="text-align: right;">16.5</td>
<td style="text-align: right;">1.1</td>
<td style="text-align: right;">10.6</td>
<td style="text-align: right;">12</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
<section id="peso-de-niños" class="level4">
<h4 class="anchored" data-anchor-id="peso-de-niños">3.1.2 Peso de niños</h4>
<div class="cell">
<div class="cell-output-display">
<p><img src="G3_Informe_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Descriptores numéricos:</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Media</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mediana</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mínimo</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Máximo</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SD</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">13.22</td>
<td style="text-align: right;">13.1</td>
<td style="text-align: right;">3.5</td>
<td style="text-align: right;">39</td>
<td style="text-align: right;">3.77</td>
<td style="text-align: right;">10.3</td>
<td style="text-align: right;">15.7</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
<section id="talla-de-niños" class="level4">
<h4 class="anchored" data-anchor-id="talla-de-niños">3.1.3 Talla de niños</h4>
<div class="cell">
<div class="cell-output-display">
<p><img src="G3_Informe_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Descriptores numéricos:</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Media</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mediana</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mínimo</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Máximo</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SD</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">88.2</td>
<td style="text-align: right;">89.8</td>
<td style="text-align: right;">51.4</td>
<td style="text-align: right;">141.7</td>
<td style="text-align: right;">12.87</td>
<td style="text-align: right;">77.9</td>
<td style="text-align: right;">98.6</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
<section id="hemoglobina-de-mujeres" class="level4">
<h4 class="anchored" data-anchor-id="hemoglobina-de-mujeres">3.1.4 Hemoglobina de mujeres</h4>
<div class="cell">
<div class="cell-output-display">
<p><img src="G3_Informe_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Descriptores numéricos:</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Media</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mediana</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mínimo</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Máximo</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SD</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">12.69</td>
<td style="text-align: right;">12.8</td>
<td style="text-align: right;">3.3</td>
<td style="text-align: right;">18.9</td>
<td style="text-align: right;">1.27</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">13.5</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
<section id="peso-de-mujeres" class="level4">
<h4 class="anchored" data-anchor-id="peso-de-mujeres">3.1.5 Peso de mujeres</h4>
<div class="cell">
<div class="cell-output-display">
<p><img src="G3_Informe_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Descriptores numéricos:</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Media</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mediana</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mínimo</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Máximo</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SD</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">62.73</td>
<td style="text-align: right;">61.5</td>
<td style="text-align: right;">24.1</td>
<td style="text-align: right;">158.9</td>
<td style="text-align: right;">13.29</td>
<td style="text-align: right;">53.5</td>
<td style="text-align: right;">70.4</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
<section id="talla-de-mujeres" class="level4">
<h4 class="anchored" data-anchor-id="talla-de-mujeres">3.1.6 Talla de mujeres</h4>
<div class="cell">
<div class="cell-output-display">
<p><img src="G3_Informe_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Descriptores numéricos:</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Media</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mediana</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Mínimo</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Máximo</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">SD</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q1</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Q3</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">152.54</td>
<td style="text-align: right;">152.5</td>
<td style="text-align: right;">127</td>
<td style="text-align: right;">179.9</td>
<td style="text-align: right;">5.67</td>
<td style="text-align: right;">148.8</td>
<td style="text-align: right;">156.2</td>
</tr>
</tbody>
</table>


</div>
</div>
</section>
</section>
<section id="variables-categóricas" class="level3">
<h3 class="anchored" data-anchor-id="variables-categóricas">3.2 Variables categóricas</h3>
<p>Las siguientes gráficas están orientadas a nuestro primer objetivo: “<strong>Describir los casos de anemia y su severidad en niños y mujeres en el Perú en el año 2022</strong>”.</p>
<section id="nivel-de-anemia-en-niños" class="level4">
<h4 class="anchored" data-anchor-id="nivel-de-anemia-en-niños">3.2.1 Nivel de anemia en niños</h4>
<div class="cell">
<div class="cell-output-display">
<p><img src="G3_Informe_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="nivel-de-anemia-en-mujeres" class="level4">
<h4 class="anchored" data-anchor-id="nivel-de-anemia-en-mujeres">3.2.2 Nivel de anemia en mujeres</h4>
<div class="cell">
<div class="cell-output-display">
<p><img src="G3_Informe_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
</section>
<section id="análisis-descriptivo-de-interacción" class="level2">
<h2 class="anchored" data-anchor-id="análisis-descriptivo-de-interacción">4. Análisis descriptivo de interacción</h2>
<section id="edad-de-niños-vs.-frecuencias-de-anemia" class="level3">
<h3 class="anchored" data-anchor-id="edad-de-niños-vs.-frecuencias-de-anemia">4.1 Edad de niños vs.&nbsp;frecuencias de anemia</h3>
<section id="edad-de-niños-vs.-frecuencia-de-anemia-leve" class="level4">
<h4 class="anchored" data-anchor-id="edad-de-niños-vs.-frecuencia-de-anemia-leve">4.1.1 Edad de niños vs.&nbsp;frecuencia de anemia leve</h4>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Promedios correspondientes a la anemia leve</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Promedio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">edad</td>
<td style="text-align: right;">28.00763</td>
</tr>
<tr class="even">
<td style="text-align: left;">peso</td>
<td style="text-align: right;">12.20270</td>
</tr>
<tr class="odd">
<td style="text-align: left;">talla</td>
<td style="text-align: right;">84.82376</td>
</tr>
<tr class="even">
<td style="text-align: left;">estado_medicion</td>
<td style="text-align: right;">0.00000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hemoglobina</td>
<td style="text-align: right;">11.41234</td>
</tr>
<tr class="even">
<td style="text-align: left;">estado_medicion_hemoglobina</td>
<td style="text-align: right;">0.00000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hemoglobina_ajustada_latitud</td>
<td style="text-align: right;">10.51752</td>
</tr>
</tbody>
</table>


</div>
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Promedios correspondientes a la anemia moderada</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Promedio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">edad</td>
<td style="text-align: right;">19.91996</td>
</tr>
<tr class="even">
<td style="text-align: left;">peso</td>
<td style="text-align: right;">10.62542</td>
</tr>
<tr class="odd">
<td style="text-align: left;">talla</td>
<td style="text-align: right;">78.36248</td>
</tr>
<tr class="even">
<td style="text-align: left;">estado_medicion</td>
<td style="text-align: right;">0.00000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hemoglobina</td>
<td style="text-align: right;">10.38763</td>
</tr>
<tr class="even">
<td style="text-align: left;">estado_medicion_hemoglobina</td>
<td style="text-align: right;">0.00000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hemoglobina_ajustada_latitud</td>
<td style="text-align: right;">9.27417</td>
</tr>
</tbody>
</table>


</div>
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Promedios correspondientes a la anemia grave</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Promedio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">edad</td>
<td style="text-align: right;">17.740741</td>
</tr>
<tr class="even">
<td style="text-align: left;">peso</td>
<td style="text-align: right;">9.659259</td>
</tr>
<tr class="odd">
<td style="text-align: left;">talla</td>
<td style="text-align: right;">76.103704</td>
</tr>
<tr class="even">
<td style="text-align: left;">estado_medicion</td>
<td style="text-align: right;">0.000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hemoglobina</td>
<td style="text-align: right;">8.111111</td>
</tr>
<tr class="even">
<td style="text-align: left;">estado_medicion_hemoglobina</td>
<td style="text-align: right;">0.000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hemoglobina_ajustada_latitud</td>
<td style="text-align: right;">6.155556</td>
</tr>
</tbody>
</table>


</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="G3_Informe_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="edad-de-niños-vs.-frecuencia-de-anemia-moderada" class="level4">
<h4 class="anchored" data-anchor-id="edad-de-niños-vs.-frecuencia-de-anemia-moderada">4.1.2 Edad de niños vs.&nbsp;frecuencia de anemia moderada</h4>
<div class="cell">
<div class="cell-output-display">
<p><img src="G3_Informe_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="edad-de-niños-vs.-frecuencia-de-anemia-grave" class="level4">
<h4 class="anchored" data-anchor-id="edad-de-niños-vs.-frecuencia-de-anemia-grave">4.1.3 Edad de niños vs.&nbsp;frecuencia de anemia grave</h4>
<div class="cell">
<div class="cell-output-display">
<p><img src="G3_Informe_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>En los casos leves de anemia en niños, observamos que las concentraciones más significativas se sitúan entre los 10 y 45 meses de edad. En los casos moderados, la mayor concentración se encuentra alrededor de los 5 y 35 meses, mientras que para los casos graves, la concentración más prominente se registra entre los 7 y 30 años. En los tres escenarios, la información se presenta altamente dispersa. Es importante destacar que el gráfico de los casos de anemia moderada exhibe una distribución que sugiere una asimetría hacia la izquierda, similar a una campana.</p>
</section>
</section>
<section id="edad-de-mujeres-vs.-frecuencia-de-anemia" class="level3">
<h3 class="anchored" data-anchor-id="edad-de-mujeres-vs.-frecuencia-de-anemia">4.2 Edad de mujeres vs.&nbsp;frecuencia de anemia</h3>
<section id="edad-de-mujeres-vs.-frecuencia-de-anemia-grave" class="level4">
<h4 class="anchored" data-anchor-id="edad-de-mujeres-vs.-frecuencia-de-anemia-grave">4.2.1 Edad de mujeres vs.&nbsp;frecuencia de anemia grave</h4>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Promedios correspondientes a la anemia leve</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Promedio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">edad</td>
<td style="text-align: right;">27.8790255</td>
</tr>
<tr class="even">
<td style="text-align: left;">peso</td>
<td style="text-align: right;">60.5611453</td>
</tr>
<tr class="odd">
<td style="text-align: left;">talla</td>
<td style="text-align: right;">152.2731028</td>
</tr>
<tr class="even">
<td style="text-align: left;">estado_medicion</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hemoglobina</td>
<td style="text-align: right;">12.1322319</td>
</tr>
<tr class="even">
<td style="text-align: left;">is_embarazada</td>
<td style="text-align: right;">0.0264632</td>
</tr>
<tr class="odd">
<td style="text-align: left;">estado_medicion_hemoglobina</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">hemoglobina_ajustada_latitud</td>
<td style="text-align: right;">11.3004761</td>
</tr>
<tr class="odd">
<td style="text-align: left;">nivel_educativo</td>
<td style="text-align: right;">1.8779053</td>
</tr>
</tbody>
</table>


</div>
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Promedios correspondientes a la anemia moderada</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Promedio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">edad</td>
<td style="text-align: right;">30.387526</td>
</tr>
<tr class="even">
<td style="text-align: left;">peso</td>
<td style="text-align: right;">62.473108</td>
</tr>
<tr class="odd">
<td style="text-align: left;">talla</td>
<td style="text-align: right;">152.708691</td>
</tr>
<tr class="even">
<td style="text-align: left;">estado_medicion</td>
<td style="text-align: right;">0.000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hemoglobina</td>
<td style="text-align: right;">9.984254</td>
</tr>
<tr class="even">
<td style="text-align: left;">is_embarazada</td>
<td style="text-align: right;">0.093047</td>
</tr>
<tr class="odd">
<td style="text-align: left;">estado_medicion_hemoglobina</td>
<td style="text-align: right;">0.000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">hemoglobina_ajustada_latitud</td>
<td style="text-align: right;">9.043967</td>
</tr>
<tr class="odd">
<td style="text-align: left;">nivel_educativo</td>
<td style="text-align: right;">1.912065</td>
</tr>
</tbody>
</table>


</div>
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Promedios correspondientes a la anemia grave</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Promedio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">edad</td>
<td style="text-align: right;">33.1566265</td>
</tr>
<tr class="even">
<td style="text-align: left;">peso</td>
<td style="text-align: right;">60.3915663</td>
</tr>
<tr class="odd">
<td style="text-align: left;">talla</td>
<td style="text-align: right;">151.6927711</td>
</tr>
<tr class="even">
<td style="text-align: left;">estado_medicion</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">hemoglobina</td>
<td style="text-align: right;">7.6277108</td>
</tr>
<tr class="even">
<td style="text-align: left;">is_embarazada</td>
<td style="text-align: right;">0.0843373</td>
</tr>
<tr class="odd">
<td style="text-align: left;">estado_medicion_hemoglobina</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">hemoglobina_ajustada_latitud</td>
<td style="text-align: right;">6.2060241</td>
</tr>
<tr class="odd">
<td style="text-align: left;">nivel_educativo</td>
<td style="text-align: right;">1.9397590</td>
</tr>
</tbody>
</table>


</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="G3_Informe_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="edad-de-mujeres-vs.-frecuencia-de-anemia-moderada" class="level4">
<h4 class="anchored" data-anchor-id="edad-de-mujeres-vs.-frecuencia-de-anemia-moderada">4.2.2 Edad de mujeres vs.&nbsp;frecuencia de anemia moderada</h4>
<div class="cell">
<div class="cell-output-display">
<p><img src="G3_Informe_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="edad-de-mujeres-vs.-frecuencia-de-anemia-grave-1" class="level4">
<h4 class="anchored" data-anchor-id="edad-de-mujeres-vs.-frecuencia-de-anemia-grave-1">4.2.3 Edad de mujeres vs.&nbsp;frecuencia de anemia grave</h4>
<div class="cell">
<div class="cell-output-display">
<p><img src="G3_Informe_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>En el caso de mujeres con anemia leve, se destaca que las concentraciones más notables se ubican alrededor de los 17 y 38 años de edad. Para los casos moderados, la mayor concentración se registra en torno a los 20 y 35 meses, mientras que en los casos graves, se observa un pico entre los 22 y 44 años. Al igual que en los casos de infantes, los datos exhiben una alta dispersión.</p>
<p>Las siguientes gráficas están orientadas a nuestro segundo objetivo: “<strong>Analizar el índice de anemia en las diversas regiones del Perú en el año 2022</strong>”.</p>
</section>
</section>
<section id="regiones-vs.-nivel-de-anemia" class="level3">
<h3 class="anchored" data-anchor-id="regiones-vs.-nivel-de-anemia">4.3 Regiones vs.&nbsp;nivel de anemia</h3>
<section id="regiones-vs.-nivel-de-anemia-en-niños" class="level4">
<h4 class="anchored" data-anchor-id="regiones-vs.-nivel-de-anemia-en-niños">4.3.1 Regiones vs.&nbsp;nivel de anemia en niños</h4>
<p>Gráfico donde se tomen las tres regiones con más casos en infantes para luego compararlos.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="G3_Informe_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="regiones-vs.-nivel-de-anemia-en-mujeres" class="level4">
<h4 class="anchored" data-anchor-id="regiones-vs.-nivel-de-anemia-en-mujeres">4.3.2 Regiones vs.&nbsp;nivel de anemia en mujeres</h4>
<div class="cell">
<div class="cell-output-display">
<p><img src="G3_Informe_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Claramente, se observa una tendencia visible en los tres casos, donde los casos leves son consistentemente predominantes. La elección de focalizar en las tres regiones con mayor incidencia de casos se fundamenta en la necesidad de dirigir mayores esfuerzos y recursos para combatir la enfermedad. Estas regiones identificadas no solo presentan una mayor incidencia, sino que también pueden ser consideradas como puntos críticos que demandan una atención prioritaria en las estrategias de prevención y control de la anemia.</p>
<p>Las siguientes gráficas están orientadas a nuestro tercer objetivo: “<strong>Describir las características sociales de los grupos vulnerables (niños y mujeres) a la anemia en el Perú en el año 2022</strong>”.</p>
</section>
</section>
<section id="características-sociales" class="level3">
<h3 class="anchored" data-anchor-id="características-sociales">4.4 Características sociales</h3>
<section id="boxplots-entre-hemoglobina-e-índice-de-riqueza-de-las-mujeres" class="level4">
<h4 class="anchored" data-anchor-id="boxplots-entre-hemoglobina-e-índice-de-riqueza-de-las-mujeres">4.4.1 <em>Boxplots</em> entre hemoglobina e índice de riqueza de las mujeres</h4>
<div class="cell">
<div class="cell-output-display">
<p><img src="G3_Informe_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>No hay mucha distinción en los casos bajos de hemoglobina por cada separación —que indica si se presenta anemia—.</p>
</section>
<section id="tipo-de-residencia-vs.-nivel-de-anemia-en-niños" class="level4">
<h4 class="anchored" data-anchor-id="tipo-de-residencia-vs.-nivel-de-anemia-en-niños">4.4.2 Tipo de residencia vs.&nbsp;nivel de anemia en niños</h4>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">1.leve</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">2.moderado</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">3.grave</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">rural</td>
<td style="text-align: right;">1891</td>
<td style="text-align: right;">967</td>
<td style="text-align: right;">13</td>
</tr>
<tr class="even">
<td style="text-align: left;">urbano</td>
<td style="text-align: right;">3223</td>
<td style="text-align: right;">1232</td>
<td style="text-align: right;">14</td>
</tr>
</tbody>
</table>


</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="G3_Informe_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Como podemos observar, la proporción entre los distintos tipos de anemia es bastante similar sea el tipo de residencia urbano o rural.</p>
</section>
</section>
</section>
<section id="probabilidad-empírica" class="level2">
<h2 class="anchored" data-anchor-id="probabilidad-empírica">5. Probabilidad empírica</h2>
<section id="variable-a-índice-de-riqueza" class="level3">
<h3 class="anchored" data-anchor-id="variable-a-índice-de-riqueza">5.1 Variable A: Índice de riqueza</h3>
<p><strong>Experimento 1:</strong> Escoger un hogar que aceptó participar en la encuesta y observar su <strong>índice de riqueza</strong>.</p>
<p><strong>Espacio muestral (</strong> <span class="math inline">\(\Omega\)</span> <strong>):</strong></p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-striped table-hover table-sm small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Unique_Values</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">4.rico</td>
</tr>
<tr class="even">
<td style="text-align: left;">5.muy_rico</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3.medio</td>
</tr>
<tr class="even">
<td style="text-align: left;">2.pobre</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1.muy_pobre</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><span class="math display">\[
\Omega = E1, \; E2, \; E3, \; E4, \; E5
\]</span></p>
<p><strong>Eventos atómicos</strong>:</p>
<ul>
<li><span class="math inline">\(E1\)</span>: Que se escoja un hogar cuyo índice de riqueza sea muy pobre</li>
<li><span class="math inline">\(E2\)</span>: Que se escoja un hogar cuyo índice de riqueza sea pobre</li>
<li><span class="math inline">\(E3\)</span>: Que se escoja un hogar cuyo índice de riqueza sea medio</li>
<li><span class="math inline">\(E4\)</span>: Que se escoja un hogar cuyo índice de riqueza sea rico</li>
<li><span class="math inline">\(E5\)</span>: Que se escoja un hogar cuyo índice de riqueza sea muy rico</li>
</ul>
<p><strong>Probabilidad de cada evento:</strong></p>
<p><span class="math display">\[
P(x) = \dfrac{f(x)}{n}
\]</span><br>
</p>
<p><span class="math inline">\(f(x)\)</span> = número de veces que se cumpla el evento en toda la muestra</p>
<p><span class="math inline">\(n\)</span> = tamaño de la muestra</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Probabilidad del índice de riqueza</caption>
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Índice de riqueza</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Probabilidad</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1.muy_pobre</td>
<td style="text-align: center;">0.3150637</td>
</tr>
<tr class="even">
<td style="text-align: center;">2.pobre</td>
<td style="text-align: center;">0.2510422</td>
</tr>
<tr class="odd">
<td style="text-align: center;">3.medio</td>
<td style="text-align: center;">0.1867001</td>
</tr>
<tr class="even">
<td style="text-align: center;">4.rico</td>
<td style="text-align: center;">0.1395003</td>
</tr>
<tr class="odd">
<td style="text-align: center;">5.muy_rico</td>
<td style="text-align: center;">0.1076937</td>
</tr>
</tbody>
</table>


</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="G3_Informe_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Comprobamos que todo sume uno (ya que son probabilidades de eventos atómicos en un espacio muestral <span class="math inline">\(\Omega\)</span> ).</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Suma de probabilidades del índice de riqueza</caption>
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Suma de probabilidades</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Probabilidad de cada evento atómico:</p>
<p>P(<strong>E1</strong>) = 0.3151</p>
<p>P(<strong>E2</strong>) = 0.251</p>
<p>P(<strong>E3</strong>) = 0.1867</p>
<p>P(<strong>E4</strong>) = 0.1395</p>
<p>Determinamos el índice de riqueza con mayor y menor probabilidad de ser escogido:</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Valores de Máximo y Mínimo de prob_riqueza</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th"></th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1.muy_pobre</td>
<td style="text-align: right;">0.3150637</td>
</tr>
<tr class="even">
<td style="text-align: left;">5.muy_rico</td>
<td style="text-align: right;">0.1076937</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Al elegir un hogar para el experimento, es más probable que sea muy pobre y menos probable que sea muy rico.</p>
</section>
<section id="variable-b-nivel-de-anemia" class="level3">
<h3 class="anchored" data-anchor-id="variable-b-nivel-de-anemia">5.2 Variable B: Nivel de anemia</h3>
<p><strong>Experimento 2:</strong> Seleccionar a un niño de entre los hogares que han aceptado participar en la prueba de hemoglobina y evaluar su <strong>nivel de anemia</strong>.</p>
<p><strong>Espacio muestral (</strong> <span class="math inline">\(\Omega\)</span> <strong>):</strong></p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Valores únicos de anemia</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Valores_unicos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">0.sin_anemia</td>
</tr>
<tr class="even">
<td style="text-align: left;">1.leve</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2.moderado</td>
</tr>
<tr class="even">
<td style="text-align: left;">3.grave</td>
</tr>
</tbody>
</table>


</div>
</div>
<p><span class="math display">\[
\Omega = E1, \; E2, \; E3, \; E4
\]</span></p>
<p><strong>Eventos atómicos</strong>:</p>
<p><strong>E1</strong>: Que se escoja un infante participante que no tenga anemia.</p>
<p><strong>E2</strong>: Que se escoja un infante participante cuyo nivel de anemia sea bajo.</p>
<p><strong>E3</strong>: Que se escoja un infante participante cuyo nivel de anemia sea moderado.</p>
<p><strong>E4</strong>: Que se escoja un infante participante cuyo nivel de anemia sea alto.</p>
<p><strong>Probabilidad por evento:</strong></p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<caption>Probabilidad de Anemia</caption>
<thead>
<tr class="header">
<th style="text-align: center;" data-quarto-table-cell-role="th">Anemia</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Probabilidad</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0.sin_anemia</td>
<td style="text-align: center;">0.6321724</td>
</tr>
<tr class="even">
<td style="text-align: center;">1.leve</td>
<td style="text-align: center;">0.2562766</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2.moderado</td>
<td style="text-align: center;">0.1101979</td>
</tr>
<tr class="even">
<td style="text-align: center;">3.grave</td>
<td style="text-align: center;">0.0013530</td>
</tr>
</tbody>
</table>


</div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="G3_Informe_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Comprobamos que todo sume uno.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p>Probabilidad de cada evento atómico:</p>
<p>P(<strong>E1</strong>) = 0.6322</p>
<p>P(<strong>E2</strong>) = 0.2563</p>
<p>P(<strong>E3</strong>) = 0.1102</p>
<p>P(<strong>E4</strong>) = 0.0014</p>
<p>Nivel de anemia con mayor y menor probabilidad de ser escogida:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "0.sin_anemia"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "3.grave"</code></pre>
</div>
</div>
<p>Es más probable que, entre los niños seleccionados, uno no presente anemia y sea menos probable que esté en un estado grave de la misma.</p>
</section>
</section>
<section id="probabilidad-condicional" class="level2">
<h2 class="anchored" data-anchor-id="probabilidad-condicional">6. Probabilidad condicional</h2>
<section id="eventos-dependientes" class="level3">
<h3 class="anchored" data-anchor-id="eventos-dependientes">6.1 Eventos dependientes</h3>
<ul>
<li><p><strong>A1</strong>: Seleccionar una mujer de la muestra que esté embarazada.</p></li>
<li><p><strong>A2</strong>: Seleccionar una mujer de la muestra que no esté embarazada.</p></li>
</ul>
<p>Probabilidad del evento <strong>A1</strong>:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    0     1 
35397   971 </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.0266993</code></pre>
</div>
</div>
<p>Probabilidad del evento <strong>A2</strong>:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9733007</code></pre>
</div>
</div>
<p>Vamos a probar que ambos eventos son <strong>dependientes</strong>, comprobando que son mutuamente excluyentes.</p>
<p>Probabilidad que ocurra <strong>A1</strong> y <strong>A2</strong>.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0</code></pre>
</div>
</div>
<p><span class="math display">\[
P(A1 \cap A2) = 0
\]</span></p>
<p>Vemos que la intersección de ambos elementos es igual a cero. Al no haber intersección entre ambos eventos, se comprueba que son eventos dependientes.</p>
<p>Dado que ambos eventos son mutuamente excluyentes y abarcan todo el espacio muestral de un experimento, estamos tratando con una partición. En este contexto, podemos aplicar el teorema de la probabilidad total para analizar la situación.</p>
<p><strong>Teorema de la probabilidad total</strong>:</p>
<p><span class="math display">\[ P(B) = P(B \mid A1)*P(A1) + P(B \mid A2)*P(A2) \]</span></p>
<p>Vamos a tomar un evento que pueda ocurrir en ambos. Este será el evento <strong>B</strong>, que representará si la mujer seleccionada tiene como mayor nivel educativo alcanzado la secundaria.</p>
<p>Probabilidad de que ocurra <strong>B</strong>:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.650077</code></pre>
</div>
</div>
<p>Observación:</p>
<p><span class="math display">\[P(x \mid y)*P(y) = P(x \cap y)\]</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Probabilidad total de B encontrada gracias al teorema de probabilidad total: 0.650077 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Probabilidad empírica de B: 0.650077 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Las probabilidades coinciden.</code></pre>
</div>
</div>
<p>Por ser una partición, también se puede comprobar el teorema de Bayes.</p>
<p><strong>Teorema de Bayes</strong>:</p>
<p><span class="math display">\[
P(A \mid B) = \frac{P(B \mid A)*P(A)}{P(B)}
\]</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.02863548</code></pre>
</div>
</div>
<p><span class="math display">\[
P(A1 \mid B) = 0.02863548
\]</span></p>
<p>La probabilidad de que la mujer escogida resulte embarazada dado que su máximo nivel educativo alcanzado es la secundaria es 0.02863548.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9713645</code></pre>
</div>
</div>
<p><span class="math display">\[
P(A2 \mid B) = 0.9713645
\]</span></p>
<p>Se puede concluir que la probabilidad de que la mujer escogida no esté embarazada dado que su máximo nivel educativo alcanzado es la secundaria es 0.9713645.</p>
</section>
<section id="eventos-independientes" class="level3">
<h3 class="anchored" data-anchor-id="eventos-independientes">6.2 Eventos independientes</h3>
<ul>
<li><p><strong>B1</strong>: Seleccionar un niño que tenga anemia dado que vive en un lugar urbano.</p></li>
<li><p><strong>B2</strong>: Seleccionar un niño que tenga anemia dado que vive en un lugar rural.</p></li>
</ul>
<p>Probabilidad del evento <strong>B1</strong>:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3293294</code></pre>
</div>
</div>
<p>Probabilidad del evento <strong>B2</strong>:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4496476</code></pre>
</div>
</div>
<p>Vamos a verificar la independencia de los eventos comparando la intersección manual de eventos con el producto de sus probabilidades. Según la regla, si dos eventos son independientes, el producto de sus probabilidades debe ser igual a la intersección de los eventos.</p>
<p><span class="math display">\[
P(B1 \cap B2) = P(B1)*P(B2)
\]</span></p>
<p>Intersección de los eventos obtenidos con combinatorias:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1480822</code></pre>
</div>
</div>
<p>Producto de las probabilidades de ambos eventos:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1480822</code></pre>
</div>
</div>
<p>Al observar que ambos resultados son iguales, podemos concluir que los dos eventos son independientes. Dado que son eventos independientes, podemos realizar las siguientes comprobaciones:</p>
<p><span class="math display">\[
P(B1 \mid B2) = B1
\]</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3293294</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3293294</code></pre>
</div>
</div>
<p><span class="math display">\[
P(B2 \mid B1) = B2
\]</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4496476</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.4496476</code></pre>
</div>
</div>
<p><span class="math display">\[
P(B1 \cap B2^c) = P(B1) * P(B2^c)
\]</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1812472</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1812472</code></pre>
</div>
</div>
<p><span class="math display">\[
P(B1^c \cap B2^c) = P(B1^c) * P(B2^c)
\]</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3691052</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3691052</code></pre>
</div>
</div>
</section>
</section>
<section id="variables-aleatorias-discretas" class="level2">
<h2 class="anchored" data-anchor-id="variables-aleatorias-discretas">7. Variables aleatorias discretas</h2>
<section id="número-de-niños-con-un-determinado-nivel-de-anemia" class="level3">
<h3 class="anchored" data-anchor-id="número-de-niños-con-un-determinado-nivel-de-anemia">7.1 Número de niños con un determinado nivel de anemia</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
0.sin_anemia       1.leve   2.moderado      3.grave 
       12615         5114         2199           27 </code></pre>
</div>
</div>
<p>La variable “<strong>Número de niños con un determinado nivel de anemia”</strong> es discreta, ya que cuenta con precisión cuántos niños se encuentran en cada categoría de anemia (sin anemia, leve, moderado, grave). La discreción proviene de que los valores son enteros y específicos.</p>
<p>Tenemos los siguientes eventos:</p>
<p><strong>L</strong>: Seleccionar a un niño con anemia cuyo nivel sea clasificado como leve.</p>
<p><strong>M</strong>: Seleccionar a un niño con anemia cuyo nivel sea clasificado como moderado.</p>
<p><strong>G</strong>: Seleccionar a un niño con anemia cuyo nivel sea clasificado como grave.</p>
<p>Vamos a tomar el evento <strong>G</strong> como nuestro éxito.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Probabilidad de anemia leve (PL): 0.6967302 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Probabilidad de anemia moderada (PM): 0.2995913 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Probabilidad de anemia grave (PG): 0.003678474 </code></pre>
</div>
</div>
<p>La probabilidad de ocurra nuestro éxito (<strong>G</strong>):</p>
<p><span class="math display">\[
P(G) = 0.0037
\]</span></p>
<ul>
<li><strong>Definimos nuestra variable aleatoria discreta</strong></li>
</ul>
<p><strong>X</strong>: Número de niños observados hasta encontrar el primer caso de anemia grave.</p>
<ul>
<li><strong>Vamos a utilizar el modelo geométrico</strong></li>
</ul>
<p><span class="math display">\[
X\sim G(p)
\]</span></p>
<ul>
<li><strong>Definimos parámetros</strong></li>
</ul>
<p><strong>p</strong>: Probabilidad que el niño tenga anemia grave.</p>
<p>Observemos un gráfico de distribución geométrica en torno a nuestra variable aleatoria discreta ’<strong>X’</strong>:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="G3_Informe_files/figure-html/unnamed-chunk-60-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li><strong>Validamos las propiedades de esperanza, varianza, desviación estándar y coeficiente de variación</strong></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Media teórica (modelo geométrico): 271.8519 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Varianza teórica (modelo geométrico): 73631.58 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Desviación estándar teórica (modelo geométrico): 271.3514 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Coeficiente de variación teórico (modelo geométrico): 0.9981591 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Media práctica (modelo geométrico): 271.8519 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Varianza práctica (modelo geométrico): 73631.58 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Desviación estándar práctica (modelo geométrico): 271.3514 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Coeficiente de variación práctico (modelo geométrico): 0.9981591 </code></pre>
</div>
</div>
<p>Los resultados teóricos y prácticos en el modelo geométrico coinciden, demostrando la eficacia del modelo para describir el número de niños observados hasta encontrar uno con anemia grave. La coherencia en estos indicadores estadísticos respalda la validez de la aproximación geométrica en este contexto.</p>
<ul>
<li><strong>Experimento</strong></li>
</ul>
<p>Se quiere averiguar la probabilidad de que se necesite observar 100 niños o menos para encontrar uno con anemia grave.</p>
<p><span class="math display">\[
P(X \leq 100)
\]</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3082465</code></pre>
</div>
</div>
<p>La probabilidad de que se necesite observar 100 niños o menos para encontrar uno con anemia grave es de aproximadamente 0.3082465.</p>
</section>
<section id="número-de-madres-con-un-determinado-nivel-educativo" class="level3">
<h3 class="anchored" data-anchor-id="número-de-madres-con-un-determinado-nivel-educativo">7.2 Número de madres con un determinado nivel educativo</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    0     1     2     3 
  451  7357 23642  4918 </code></pre>
</div>
</div>
<p>La variable “<strong>Número de madres con un determinado nivel educativo</strong>” es discreta, ya que cuenta con precisión cuántas madres se encuentran en cada categoría educativa (primaria, secundaria, universitaria, etc.). La discreción proviene de que los valores son enteros y específicos.</p>
<p>Tenemos los siguientes eventos:</p>
<p><strong>N</strong>: Seleccionar a una madre que participó en la encuesta y que no haya recibido educación.</p>
<p><strong>P</strong>: Seleccionar a una madre que participó en la encuesta y su nivel educativo máximo alcanzado es la primaria.</p>
<p><strong>S</strong>: Seleccionar a una madre que participó en la encuesta y su nivel educativo máximo alcanzado es secundaria.</p>
<p><strong>U</strong>: Seleccionar a una madre que participó en la encuesta y su nivel educativo máximo alcanzado es la superior.</p>
<p>Vamos a tomar el evento <strong>S</strong> como nuestro éxito.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Probabilidad de no educación (PN): 0.01240101 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Probabilidad de educación primaria (PP): 0.2022932 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Probabilidad de educación secundaria (PS): 0.650077 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Probabilidad de educación superior (PU): 0.1352288 </code></pre>
</div>
</div>
<p>La probabilidad de que ocurra el éxito (<strong>S</strong>):</p>
<p><span class="math display">\[
P(S) = 0.65
\]</span></p>
<ul>
<li><strong>Definimos nuestra variable aleatoria discreta</strong></li>
</ul>
<p><strong>X</strong>: Número de madres cuyo mayor nivel educativo alcanzado sea la secundaria en una muestra sin reemplazo de 100.</p>
<ul>
<li><strong>Vamos a utilizar el modelo hipergeométrico:</strong></li>
</ul>
<p><span class="math display">\[
X \sim H(N,r,n)
\]</span></p>
<ul>
<li><strong>Definimos parámetros</strong></li>
</ul>
<p><strong>N</strong>: Representa el total de mujeres que participaron en la encuesta.</p>
<p><strong>r</strong>: Indica el número de mujeres cuyo nivel educativo máximo es la secundaria.</p>
<p><strong>n</strong>: Es el número de elementos que seleccionaremos de este conjunto total.</p>
<p>Observemos una gráfica de distribución hipergeométrica en torno a los parámetros descritos y a nuestra variable aleatoria discreta ’<strong>X’</strong> en una muestra de 100:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="G3_Informe_files/figure-html/unnamed-chunk-65-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li><strong>Validamos las propiedades de esperanza, varianza, desviación estándar y coeficiente de variación</strong></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Media teórica: 65.0077 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Varianza teórica: 22.68576 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Desviación estándar teórica: 4.762958 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Coeficiente de variación teórico: 0.07326759 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Media práctica: 65.0077 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Varianza práctica: 22.68576 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Desviación estándar práctica: 4.762958 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Coeficiente de variación práctico: 0.07326759 </code></pre>
</div>
</div>
<p>Los resultados teóricos y prácticos en el modelo hipergeométrico coinciden, demostrando la eficacia del modelo para describir el número de niños observados hasta encontrar uno con anemia grave. La coherencia en estos indicadores estadísticos respalda la validez de la aproximación hipergeométrica en este contexto.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(XX, <span class="fu">dhyper</span>(<span class="dv">0</span><span class="sc">:</span>n, r, (N <span class="sc">-</span> r), n), <span class="at">type =</span> <span class="st">"h"</span>, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"blue"</span>,</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"P(X = x)"</span>, <span class="at">xlab =</span> <span class="st">"Número de estudiantes con educación secundaria en una muestra de 100"</span>,</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Distribución Hipergeométrica"</span>,</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">sub =</span> <span class="fu">paste</span>(<span class="st">"Total de estudiantes con educación secundaria:"</span>, S))</span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> mu_e, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lty =</span> <span class="dv">2</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">v =</span> <span class="fu">c</span>(mu_e <span class="sc">-</span> sigma_e, mu_e <span class="sc">+</span> sigma_e), <span class="at">col =</span> <span class="st">"black"</span>, <span class="at">lty =</span> <span class="dv">3</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"topleft"</span>, <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"Probabilidades"</span>, <span class="st">"Media"</span>, <span class="st">"Media ± 1 Desviación Estándar"</span>),</span>
<span id="cb54-11"><a href="#cb54-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"blue"</span>, <span class="st">"red"</span>, <span class="st">"black"</span>), <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>), <span class="at">lwd =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="G3_Informe_files/figure-html/unnamed-chunk-67-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"La línea roja representa la media teórica de la distribución hipergeométrica.</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>La línea roja representa la media teórica de la distribución hipergeométrica.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Las líneas verdes indican la media ± 1 desviación estándar.</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Las líneas verdes indican la media ± 1 desviación estándar.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"Esto ayuda a visualizar la dispersión de la distribución.</span><span class="sc">\n</span><span class="st">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Esto ayuda a visualizar la dispersión de la distribución.</code></pre>
</div>
</div>
<ul>
<li><strong>Experimento</strong></li>
</ul>
<p>Deseamos determinar la probabilidad de seleccionar al menos 50 mujeres cuyo nivel educativo máximo sea la secundaria de una muestra de 100 mujeres.</p>
<p><span class="math display">\[
P(X \geq 50)
\]</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.9985772</code></pre>
</div>
</div>
<p>Dado el resultado, es altamente probable encontrar en esta muestra de tamaño reducido a más de 50 mujeres cuyo máximo nivel educativo fue la secundaria. Esto se debe a la alta probabilidad del evento <strong>S</strong> (<strong>0.65</strong>).</p>
</section>
</section>
<section id="variables-aleatorias-continuas" class="level2">
<h2 class="anchored" data-anchor-id="variables-aleatorias-continuas">8. Variables aleatorias continuas</h2>
<section id="hemoglobina-ajustada-en-función-de-la-latitud-gdl" class="level3">
<h3 class="anchored" data-anchor-id="hemoglobina-ajustada-en-función-de-la-latitud-gdl">8.1 Hemoglobina ajustada en función de la latitud (<span class="math inline">\(g/dl\)</span>)</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  [1] 12.3 12.6 14.4 13.3 15.0 13.0 14.2 14.3 12.0 13.5  8.1 14.1 11.6 12.2 10.9
 [16] 13.4 14.5 13.9 14.6 12.5 11.8 12.7 13.8 12.1 11.9 13.6 13.1 14.0 13.2 11.5
 [31] 12.9 10.3  8.3 11.2 11.0 13.7 14.7 12.8 12.4 11.1  8.9 11.3  9.9 15.2 10.6
 [46] 10.8  9.1 10.5 10.7 10.1 11.7  9.0 10.2 11.4  9.7  9.4  9.3 14.8  7.7 15.1
 [61] 15.3 15.4  9.8  9.6 10.4  8.4  7.5 14.9 15.5 16.5  9.2 15.8  8.5 15.6 15.7
 [76]  8.8  9.5  7.4  8.7  7.9  8.0  5.5  6.5 16.1 16.0 16.4 15.9  7.0 10.0  8.2
 [91]  5.8  7.2  5.9 18.1  7.8  7.6 17.0  6.7  6.8  8.6 16.7 16.2 16.6  6.1  6.4
[106] 18.6  6.6 16.3 18.3 18.9  7.3  5.2 17.7  7.1  6.3  6.9 17.2  5.7 17.5 17.1
[121] 17.8 18.4  6.2 16.8  3.3 16.9  4.1  4.6  6.0  3.5  5.0  4.3</code></pre>
</div>
</div>
<p>La continuidad de esta variable se relaciona con la naturaleza de la medición. En un contexto práctico, los niveles de hemoglobina pueden variar de manera suave y gradual, y no se limitan a valores discretos específicos. La posibilidad de tener un número infinito de valores en cualquier rango dado hace que la hemoglobina sea una variable continua.</p>
<ul>
<li><strong>Validamos las propiedades de esperanza, varianza, desviación estándar y coeficiente de variación</strong></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Esperanza (media): 12.68532 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Varianza: 1.613424 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Desviación estándar: 1.270206 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Coeficiente de variación: 0.100132 </code></pre>
</div>
</div>
<ul>
<li><strong>Identificamos la distribución</strong></li>
</ul>
<p><strong>Primero</strong>, generamos un histograma y un gráfico de densidad kernel para obtener una visión integral de la distribución de los datos y comprender mejor su comportamiento.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="G3_Informe_files/figure-html/unnamed-chunk-71-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="G3_Informe_files/figure-html/unnamed-chunk-71-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Segundo</strong>, utilizamos la biblioteca <strong><code>rriskDistributions</code></strong> para realizar ajustes de distribuciones continuas a los datos de la variable <strong><code>hemoglobina_ajustada_latitud</code></strong> almacenados en el vector <strong><code>x</code></strong>. Luego, visualizamos los datos utilizando la función <strong><code>View(x)</code></strong> y procedemos a realizar el ajuste con la función <strong><code>fit.cont(x)</code></strong>.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>
Begin fitting distributions ---------------------------------------</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>* fitting normal distribution ... OK</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>* fitting Cauchy  distribution ... OK</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>* fitting logistic distribution ... OK</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>* fitting beta distribution ... failed</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>* fitting exponential distribution ... OK</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>* fitting chi-square distribution ... OK</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>* fitting uniform distribution ... OK</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>* fitting gamma distribution ... OK</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>* fitting lognormal distribution ... OK</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>* fitting Weibull distribution ... OK</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>* fitting F-distribution ... OK</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>* fitting Student's t-distribution ... OK</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>* fitting Gompertz distribution ... failed</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>* fitting triangular distribution ... failed</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>End fitting distributions -----------------------------------------</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                  logL       AIC       BIC Chisq(value) Chisq(p) AD(value)
Normal       -60301.93 120607.85 120624.86      6521.16        0    207.40
Cauchy       -63650.12 127304.25 127321.25      7455.54        0    439.59
Logistic     -59114.62 118233.24 118250.24      1508.42        0     60.75
Exponential -128758.91 257519.82 257528.32    277332.86        0  13693.59
Chi-square   -93143.05  186288.1  186296.6     78517.47        0   7504.65
Uniform           NULL      NULL      NULL          Inf        0       Inf
Gamma        -61793.91 123591.82 123608.83     16452.41        0    382.36
Lognormal    -62772.61 125549.23 125566.23     25285.31        0    499.63
Weibull      -59594.86 119193.72 119210.72      1554.11        0       Inf
F           -172527.44 345058.88 345075.88   1018217.99        0  21057.38
Student     -201840.58 403683.16 403691.66   2323104.93        0  37284.61
               H(AD) KS(value)    H(KS)
Normal      rejected      0.06 rejected
Cauchy      rejected      0.08 rejected
Logistic    rejected      0.03 rejected
Exponential rejected      0.52 rejected
Chi-square      NULL      0.34 rejected
Uniform         NULL      0.11 rejected
Gamma       rejected      0.08 rejected
Lognormal   rejected      0.09 rejected
Weibull     rejected      0.05 rejected
F               NULL      0.67 rejected
Student         NULL      0.82 rejected</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Chosen continuous distribution is: Normal (norm)
Fitted parameters are: 
     mean        sd 
12.685317  1.270189 </code></pre>
</div>
</div>
<p>Los resultados del ajuste indican que la distribución de los datos se asemeja más a una distribución normal. Esta conclusión encuentra respaldo en la forma del gráfico de densidad de kernel, el cual exhibía una configuración similar a la característica campana asociada a la distribución normal.</p>
<ul>
<li><strong>Vamos a utilizar el modelo de distribución normal:</strong></li>
</ul>
<p><span class="math display">\[ X \sim N(\mu,\sigma^2
) \]</span></p>
<ul>
<li><strong>Definimos parámetros</strong></li>
</ul>
<p><span class="math inline">\(\mu\)</span> : Es el valor de la media de la variable.</p>
<p><span class="math inline">\(\sigma^2\)</span> : Es el valor de la varianza de la variable.</p>
<p>Observemos una gráfica de distribución normal en torno a los parámetros descritos:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="G3_Informe_files/figure-html/unnamed-chunk-73-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li><strong>Definimos nuestra variable aleatoria continua</strong></li>
</ul>
<p><strong>X</strong>: Nivel de hemoglobina en <span class="math inline">\(g/dl\)</span> de una madre encuestada.</p>
<ul>
<li><strong>Experimento</strong></li>
</ul>
<p>Probabilidad de que una madre tenga menos de 12 <span class="math inline">\(g/dl\)</span> hemoglobina.</p>
<p><span class="math display">\[
P(X &lt; 12)
\]</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2947574</code></pre>
</div>
</div>
<p>La probabilidad de que una madre tenga 12 <span class="math inline">\(g/dl\)</span> o menos de hemoglobina, según el resultado proporcionado (0.2947574), indica que hay una probabilidad relativamente baja de que una madre seleccionada al azar tenga una concentración de hemoglobina de 12 <span class="math inline">\(g/dl\)</span> o inferior, según la distribución normal ajustada a los datos.</p>
<p>Escogimos ese rango de hemoglobina debido a que es el rango en el que empieza la anemia. Por lo tanto, esperamos que sea cercano a lo siguiente:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
0.sin_anemia       1.leve   2.moderado      3.grave 
       28165         7142          978           83 </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2255554</code></pre>
</div>
</div>
<p>Los resultados se aproximan.</p>
</section>
<section id="peso-kg" class="level3">
<h3 class="anchored" data-anchor-id="peso-kg">8.2 Peso (<span class="math inline">\(kg\)</span>)</h3>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  [1]  65.9  62.6  58.3  59.8  67.6  45.6  53.9  55.8  77.5  62.4  93.1  68.3
 [13]  61.6  47.7  72.1  74.4  56.1  55.0  76.0  62.2  70.6  63.0  64.9  67.3
 [25]  45.7  49.6  48.9  75.3  57.4  60.5  66.2  65.2  62.1  70.0  63.6  61.1
 [37]  42.2  70.4  59.9  49.7  55.4  56.2  78.2  60.2  55.3  45.5  53.7  55.5
 [49]  68.4  36.7  71.5  70.9  41.2  42.1  58.6  96.4  56.6  53.4  44.2  52.2
 [61]  75.5  47.0  48.3  71.3  61.9  83.3  65.1  54.1  70.7  40.1  72.6  54.9
 [73]  75.4  59.4  40.7  73.4  75.6  44.7  50.9  48.4  68.7  47.3  69.2  41.8
 [85]  72.5  60.3  48.6 111.9  55.1  70.5  52.1  63.1  74.8  60.6  68.1  39.3
 [97]  48.5  76.1  69.9  51.6  75.7  59.2  62.0  43.8  74.5  67.0  49.9  73.2
[109]  66.8  61.3  48.2 113.3  53.6  81.4  78.3  44.9  71.4  51.8  62.7  65.6
[121]  66.0  62.5  64.7  47.6  57.8  75.9  55.9  51.4  55.2  44.4  54.7  79.2
[133]  49.5  62.9  62.8  57.2  57.7  60.0  85.1  60.9  71.1  53.3  66.3  64.3
[145]  40.2  45.4  41.6  44.0  40.9  58.2  42.5  43.2  63.9  46.7  66.6  45.9
[157]  42.0  50.0  50.8  80.6  59.7  51.1  29.2  63.2  47.5  44.8  56.5  46.9
[169]  38.3  35.4  44.6  64.6  70.8  72.0  79.0  59.3  56.7  39.5  74.3  68.5
[181]  68.8  78.5 100.4  54.0  67.4  82.7  57.3  60.4  57.0  47.1  46.5  54.4
[193]  47.2  40.0  54.5  37.9  60.1  43.9  39.8  52.0  52.6  54.2  44.3  68.0
[205]  53.5  64.2  76.9  53.1  35.6  60.8  52.4  56.8  54.6  57.9  49.3  46.1
[217]  65.7  76.8  54.8  61.7  69.3  57.5  78.1  90.2  73.3  66.9  77.2  50.2
[229]  64.4  45.3  65.3  47.8  73.6  56.9  71.7  51.0  58.4  53.2  41.7  49.0
[241]  41.1  55.7  84.5  70.1  52.7  71.8  56.0  56.3  70.2  69.6  52.5  61.4
[253]  49.1  69.5  65.4  63.7  58.5  47.9  85.0  72.2  58.0  64.5  47.4  76.7
[265]  46.8  84.2  49.4  46.4  57.1  50.7  61.8  77.8  40.6  45.0  48.7  79.3
[277]  49.8  52.3  71.2  72.7  61.0  45.2  41.5  69.4  50.3  73.7  49.2  43.7
[289]  63.8  69.7  69.1  86.6  61.2  86.1  89.6  83.2  62.3  58.8 104.9  50.6
[301]  67.5  81.8  54.3  42.3  85.8  75.0 101.7 114.7  66.1  64.8  39.1  83.5
[313]  87.5  41.0  72.3  50.5  65.0  74.6  77.9  42.8  65.8  32.3  93.8  50.4
[325]  84.7  84.1  81.3  77.4  38.4  73.0 118.5  82.0  75.8  77.0  69.0  65.5
[337]  58.9  64.1  73.9  66.4  91.4  55.6  74.9  83.8  89.5  80.7  81.9  83.6
[349]  78.9  85.7  59.6  42.6  43.0  85.4  69.8  81.1  53.0  61.5  89.2  68.6
[361]  76.3  81.5  58.7  57.6  94.8  73.5  52.8  82.3  78.7  67.1  76.5  51.9
[373]  67.7  91.3  63.3  63.5  74.7  59.1  51.3  80.9  68.9  77.1  71.6  64.0
[385]  48.0  43.3  79.9  35.1  39.0  59.0  56.4  34.7  35.3  52.9  83.7  85.9
[397]  51.7  70.3  76.2  37.3  79.1  38.0  67.2  79.4  59.5  75.1  72.9  78.8
[409]  42.4  50.1  51.5  84.3  77.6  46.6  68.2  72.8  45.8  73.1  80.3  74.1
[421]  81.0  74.0  82.8  85.3  32.5  43.5  46.2  71.9  33.1  86.8  51.2  92.5
[433]  75.2  36.4  30.1  92.6  38.9  78.4  92.2  39.7  30.9  48.8  36.5  72.4
[445]  43.1  45.1  60.7  84.6 111.2  58.1  38.6  31.7  32.0  46.0  35.8  86.3
[457]  92.4  88.8  43.6  53.8  86.4  80.4  36.1  88.2  66.7  93.5  87.7 109.1
[469]  83.4  88.1  85.5  76.4  95.9  88.6  82.6 103.4  82.1  82.4  95.2  88.9
[481]  94.2  80.1  91.2  91.7  67.8  88.4  46.3  78.0  86.7  86.5 116.8  66.5
[493]  90.8  84.4  74.2  77.7  40.5  89.7  77.3  44.1  34.0 106.4  48.1  42.9
[505]  94.1 101.0  81.7 107.5  87.1  76.6  86.0  84.8  37.0  91.1  41.3  33.2
[517]  84.0  99.0  44.5  63.4  67.9  98.0  40.4  78.6  41.4  86.2  79.6  96.8
[529]  42.7  87.0  37.6  37.2  38.7  82.2  43.4  40.8  94.0  39.9  83.0  95.7
[541]  84.9  33.5  41.9  85.6  73.8  81.6  98.9  35.0  33.6  37.7  79.5  90.5
[553]  39.4  92.0  99.9  95.3 115.3 103.9 106.8  71.0  91.6  40.3  93.0  90.0
[565]  80.5  87.2  90.6  95.1  82.5  91.8 114.2  89.1  90.3 116.6 103.3  90.9
[577]  98.3  95.0 104.2  87.3  93.4  82.9  36.3  31.6  37.5  34.2  79.7  81.2
[589]  33.9  34.8  34.3  29.0  32.8  32.7  35.2 102.3  38.1  39.2  89.4 105.0
[601]  92.7 107.2  85.2  80.0  88.0 101.3  33.4  37.4  83.9 105.6  96.0  39.6
[613]  99.1  99.3 102.7 100.3 108.5 128.7 103.7  98.4 106.9 108.0  87.9  80.8
[625]  94.4 113.2  94.5 101.1  37.1  97.6 102.8  35.9  88.7  91.5  38.8  34.6
[637]  90.7  97.2  88.5  36.9 103.2  38.2  95.6 137.4  92.1  36.2  95.4 100.5
[649]  96.2  91.0  93.6  79.8  28.6  31.9  92.3  80.2 122.2  96.5 104.7  89.8
[661]  36.6  87.8  96.1  31.8  30.7 100.7  92.9  27.0 127.9  94.7  35.7 107.3
[673] 120.1 103.5  97.5  90.1 108.3  98.1 107.6  96.6  91.9 127.7 140.6  30.4
[685] 117.5  89.9 105.5 110.2  88.3  34.9 100.1  83.1 120.0  89.3  99.2  87.6
[697]  99.8 102.9  93.2 123.7 108.8  86.9  97.4 102.5  93.7 105.2  99.4  94.3
[709]  97.1  33.3  34.4 107.0  36.8 102.2  96.7  36.0 102.0 110.0 104.3  87.4
[721] 103.1 105.3  93.3  90.4 115.0 132.5 110.6 103.0  38.5  97.3 128.5 112.2
[733]  89.0  97.9 106.5 128.3 134.4 113.4 116.1 101.2  34.5 100.6  35.5 104.1
[745]  98.2 114.9  97.0 109.0  33.7  31.1 100.9  31.0  37.8 106.3  99.5 112.0
[757] 118.6  97.7  93.9  94.6 112.1  98.8 112.3 120.8 101.4  95.5 118.3 107.7
[769]  29.1 102.4 104.4 117.4 109.5  99.7 101.8 109.4  99.6 108.2  32.2  27.3
[781]  30.8 117.8  29.4 107.8 101.6 113.0  92.8 113.7  33.0 100.0  30.6  33.8
[793] 102.6 107.4  96.3  32.6  95.8  28.0 106.2  96.9 126.2  98.7 104.6 101.9
[805] 122.9 100.8  94.9 115.2 109.6  97.8  32.4  27.9 120.6  98.6 121.2 138.0
[817] 111.5 108.1  31.5 103.8 157.2 121.4  28.7  32.9 112.7 107.1 119.2  32.1
[829] 103.6 110.8 105.7 125.6 113.8 107.9 126.7 105.4 111.3 114.8 105.9 113.6
[841]  24.1  26.5 137.1 101.5 128.0 114.4  30.2  98.5 116.9 154.0 115.9 109.2
[853]  34.1 149.5  30.3  25.0 136.4 119.0 148.0 128.9 119.1  31.4 111.0 108.4
[865]  31.3  25.5  27.6 120.5 114.1 108.6 108.7 105.8 106.6 118.0 122.5 158.6
[877]  28.4 104.8  28.2  29.3  29.6 119.3  28.9 113.5 124.0 121.6 127.3 111.6
[889] 105.1 104.0 158.9  27.7 106.1 121.0 117.0  29.8  26.2 109.3</code></pre>
</div>
</div>
<p>La naturaleza continua de la variable de peso se relaciona directamente con la forma en que se mide. En un contexto práctico, los valores de peso pueden variar de manera suave y gradual, extendiéndose a lo largo de un rango continuo. A diferencia de las medidas discretas, como contar el número de elementos, el peso tiene la capacidad de tomar un número infinito de valores en cualquier intervalo dado.</p>
<ul>
<li><strong>Validamos las propiedades de esperanza, varianza, desviación estándar y coeficiente de variación</strong></li>
</ul>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Esperanza (media): 62.72915 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Varianza: 176.5763 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Desviación estándar: 13.2882 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Coeficiente de variación: 0.2118346 </code></pre>
</div>
</div>
<ul>
<li><strong>Identificamos la distribución</strong></li>
</ul>
<p><strong>Primero</strong>, generamos un histograma y un gráfico de densidad kernel para obtener una visión integral de la distribución de los datos y comprender mejor su comportamiento.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="G3_Informe_files/figure-html/unnamed-chunk-79-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="G3_Informe_files/figure-html/unnamed-chunk-79-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p><strong>Segundo</strong>, utilizamos la biblioteca <strong><code>rriskDistributions</code></strong> para realizar ajustes de distribuciones continuas a los datos de la variable <strong><code>hemoglobina_ajustada_latitud</code></strong> almacenados en el vector <strong><code>x</code></strong>. Luego, visualizamos los datos utilizando la función <strong><code>View(x)</code></strong> y procedemos a realizar el ajuste con la función <strong><code>fit.cont(x)</code></strong>.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>
Begin fitting distributions ---------------------------------------</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>* fitting normal distribution ... OK</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>* fitting Cauchy  distribution ... OK</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>* fitting logistic distribution ... OK</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>* fitting beta distribution ... failed</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>* fitting exponential distribution ... OK</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>* fitting chi-square distribution ... OK</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>* fitting uniform distribution ... OK</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>* fitting gamma distribution ... OK</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>* fitting lognormal distribution ... OK</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>* fitting Weibull distribution ... OK</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>* fitting F-distribution ... OK</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>* fitting Student's t-distribution ... OK</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>* fitting Gompertz distribution ... failed</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>* fitting triangular distribution ... failed</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>End fitting distributions -----------------------------------------</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                  logL       AIC       BIC Chisq(value) Chisq(p) AD(value)
Normal      -145682.98 291369.96 291386.96      2812.19        0    153.71
Cauchy      -150765.04 301534.09 301551.09      9227.58        0    532.67
Logistic    -145308.34 290620.68 290637.68      1497.45        0     90.01
Exponential -186888.83 373779.66 373788.16    100648.47        0  10654.10
Chi-square  -145545.44 291092.89 291101.39      3653.23        0    212.57
Uniform           NULL      NULL      NULL          Inf        0       Inf
Gamma       -144578.42 289160.83 289177.84       389.43        0     17.56
Lognormal    -144464.1  288932.2 288949.21       184.92        0      4.41
Weibull     -147674.98 295353.95 295370.96      5996.56        0       Inf
F           -246643.07 493290.14 493307.14    680752.81        0  18742.19
Student     -273782.87 547567.74 547576.24   1475954.66        0  34826.38
               H(AD) KS(value)    H(KS)
Normal      rejected      0.04 rejected
Cauchy      rejected      0.09 rejected
Logistic    rejected      0.03 rejected
Exponential rejected      0.45 rejected
Chi-square      NULL      0.04 rejected
Uniform         NULL      0.09 rejected
Gamma       rejected      0.02 rejected
Lognormal   rejected      0.01 rejected
Weibull     rejected      0.07 rejected
F               NULL      0.65 rejected
Student         NULL      0.81 rejected</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Chosen continuous distribution is: Normal (norm)
Fitted parameters are: 
    mean       sd 
62.72915 13.28802 </code></pre>
</div>
</div>
<p>Los resultados del ajuste indican que la distribución de los datos se asemeja más a una distribución normal. Esta conclusión encuentra respaldo en la forma del gráfico de densidad de kernel, el cual exhibía una configuración similar a la característica campana asociada a la distribución normal.</p>
<ul>
<li><strong>Vamos a utilizar el modelo de distribución normal:</strong></li>
</ul>
<p><span class="math display">\[ X \sim N(\mu, \; \sigma^2 ) \]</span></p>
<ul>
<li><strong>Definimos parámetros</strong></li>
</ul>
<p><span class="math inline">\(\mu\)</span> : Es el valor de la media de la variable.</p>
<p><span class="math inline">\(\sigma^2\)</span> : Es el valor de la varianza de la variable.</p>
<p>Observemos una gráfica de distribución normal en torno a los parámetros descritos:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="G3_Informe_files/figure-html/unnamed-chunk-81-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li><strong>Definimos nuestra variable aleatoria continua</strong></li>
</ul>
<p><span class="math inline">\(X\)</span>: Peso en <span class="math inline">\(kg\)</span> de una madre encuestada.</p>
<ul>
<li><strong>Experimento</strong></li>
</ul>
<p>Probabilidad de que una madre pese más de 70 <span class="math inline">\(kg\)</span>.</p>
<p><span class="math display">\[
P(X &gt; 70)
\]</span></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2921298</code></pre>
</div>
</div>
<p>La probabilidad de que una madre pese más de 70 <span class="math inline">\(kg\)</span>, según el resultado proporcionado (0.2921298), indica que hay una probabilidad relativamente baja de que una madre seleccionada al azar tenga un peso de más de 70 <span class="math inline">\(kg\)</span>, según la distribución de la variable aleatoria continua ajustada a los datos.</p>
</section>
</section>
<section id="conclusiones" class="level2">
<h2 class="anchored" data-anchor-id="conclusiones">9. Conclusiones</h2>
<p>Con respecto al primer objetivo, podemos concluir lo siguiente:</p>
<ul>
<li><p>Los niños menores a 10 meses son más propensos a desarrollar cualquier tipo de anemia.</p></li>
<li><p>Las mujeres menores de 20 años son más propensas a desarrollar anemia leve, mientras que las mayores de 30 suelen desarrollar anemia moderada o grave.</p></li>
</ul>
<p>Con respecto al segundo objetivo, podemos concluir lo siguiente:</p>
<ul>
<li>Ucayali es la región con mayor incidencia de anemia moderada, superando a Lima a pesar de tener menos población.</li>
</ul>
<p>Con respecto al tercer objetivo, podemos concluir lo siguiente:</p>
<ul>
<li>Los niños que viven en una residencia rural son más propensos a tener anemia moderada que los que viven en residencia urbana.</li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>